# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(default='+91', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_no',
            field=models.CharField(default='+91', max_length=12),
        ),
    ]
