# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20171020_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
