# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='name1',
        ),
    ]
